### ISSUE TITLE
joiner 0.6.0 not generating correct join/alias?

### ISSUE THREAD

**Issue by rogerkk** [pat/joiner#10]
I've come across a join (and corresponding alias) that is generated in the config in rails 6.0 / thinking-sphinx 5.4 / joiner 0.5, but is missing in rails 6.1 / thinking-sphinx 5.4 / joiner 0.6. It's consequently causing indexing to fail.

Not feeling terribly comfortable trying to dig into this bug myself, so let me just try to describe the case as best I can. Sorry for the verbosity – hopefully you can quickly dig into the interesting bits!

## Stripped-down index definition:

```ruby
ThinkingSphinx::Index.define :doctor,
                             name: :doctor_ads,
                             with: :active_record,
                             delta: ThinkingSphinx::Deltas::DelayedDelta do

  indexes organizations.name, as: :practice_name, sortable: true

  join search_advertisement_deal # Without this the generated config seems fine.
end
```

## Simplified model setup

```ruby
class Person < ApplicationRecord
    has_many :person_organizations, foreign_key: :person_id

    has_many :organizations,
                      through:     :person_organizations,
                      foreign_key: :organization_id

    has_many :search_advertisement_deal,
               through: :organizations,
               class_name: 'CommercialDeal',
               as: :commercializable
end

class Doctor < Person; end

class PersonOrganization < ApplicationRecord
    has_many :organizations,
             through:     :person_organizations,
             foreign_key: :organization_id
end

class Organization < ApplicationRecord
  has_many :people,
           through: :person_organizations,
           foreign_key: 'person_id' do
  has_many :search_advertisement_deal,
           class_name: 'CommercialDeal',
           as: :commercializable
end

class CommercialDeal < ApplicationRecord
  belongs_to :commercializable, polymorphic: true, touch: true
end
```

### Rails 6.0 / joiner 0.5.0 (working)

```sql
SELECT
  "people"."id" * 37 + 10 AS "id",
  COALESCE(
    NULLIF("people"."type", ''),
    'Doctor'
  ) AS "sphinx_internal_class_name",
  array_to_string(
    array_agg(
      DISTINCT "organizations_people"."name"
    ),
    ' '
  ) AS "practice_name",
  "people"."id" AS "sphinx_internal_id",
  COALESCE(
    NULLIF("people"."type", ''),
    'Doctor'
  ) AS "sphinx_internal_class",
  0 AS "sphinx_deleted"
FROM
  "people"
  LEFT OUTER JOIN "person_organizations" ON "person_organizations"."person_id" = "people"."id"
  LEFT OUTER JOIN "organizations" ON "organizations"."id" = "person_organizations"."organization_id"
  AND (
    person_organizations.active = TRUE
  )
  LEFT OUTER JOIN "commercial_deals" ON "commercial_deals"."commercializable_type" = 'Organization'
  AND "commercial_deals"."active" = TRUE
  AND "commercial_deals"."deal_type" = 1
  AND "commercial_deals"."commercializable_id" = "organizations"."id"
  LEFT OUTER JOIN "person_organizations" "person_organizations_people_join" ON "person_organizations_people_join"."person_id" = "people"."id"
  LEFT OUTER JOIN "organizations" "organizations_people" ON "organizations_people"."id" = "person_organizations_people_join"."organization_id"
  AND (
    person_organizations.active = TRUE
  )
WHERE
  "people"."type" = 'Doctor'
  AND (
    "people"."id" BETWEEN $start
    AND $end
  )
GROUP BY
  "people"."id",
  "people"."id",
  "people"."type" sql_query_range =
SELECT
  COALESCE(
    MIN("people"."id"),
    1
  ),
  COALESCE(
    MAX("people"."id"),
    1
  )
FROM
  "people"
WHERE
  "people"."type" = 'Doctor'
```

### Rails 6.1 / joiner 0.6.0 (failing)

Notice the LEFT OUTER JOIN on ```organizations``` with the alias ```organizations_people``` that was present in the previous example is completely missing here, but it's being referenced from the SELECT.

```sql
SELECT 
  "people"."id" * 40 + 10 AS "id", 
  COALESCE(
    NULLIF("people"."type", ''), 
    'Doctor'
  ) AS "sphinx_internal_class_name", 
  array_to_string(
    array_agg(
      DISTINCT "organizations_people"."name"
    ), 
    ' '
  ) AS "practice_name", 
  "people"."id" AS "sphinx_internal_id", 
  COALESCE(
    NULLIF("people"."type", ''), 
    'Doctor'
  ) AS "sphinx_internal_class", 
  0 AS "sphinx_deleted" 
FROM 
  "people" 
  LEFT OUTER JOIN "person_organizations" ON "person_organizations"."person_id" = "people"."id" 
  LEFT OUTER JOIN "organizations" ON "organizations"."id" = "person_organizations"."organization_id" 
  LEFT OUTER JOIN "commercial_deals" ON "commercial_deals"."commercializable_type" = 'Organization' 
  AND "commercial_deals"."active" = TRUE 
  AND "commercial_deals"."deal_type" = 1 
  AND "commercial_deals"."commercializable_id" = "organizations"."id" 
WHERE 
  "people"."type" = 'Doctor' 
  AND (
    "people"."id" BETWEEN $start 
    AND $end 
    AND commercial_deals.id IS NOT NULL
  ) 
GROUP BY 
  "people"."id", 
  "people"."id", 
  "people"."type"
```

**Comment by rogerkk** [comment]
Let me know if anything needs clarification! :pray: :slightly_smiling_face:

**Comment by pat** [comment]
Hi Roger - sorry I haven't gotten back to you sooner. I'm struggling a little to get my head around all of this - both the model hierarchy (is Doctor a subclass of Person? And if so, does Person have an `organizations` association for `search_advertisement_deal` to use? Also, why is the join required?

But also: Joiner is a small yet complex beast, and every time ActiveRecord changes it takes me a while to get my head back in the space. I'm wondering if it's possible for you to add some failing specs in a PR, and I can debug further from there? (See `spec/internal/db/schema.rb`, add appropriate models, and see if a spec can be wrangled into `spec/acceptance/joiner_spec.rb`)

**Comment by rogerkk** [comment]
Thanks Pat! I see now that I was sloppy when making the example. Yes, Doctor is a subclass of Person. And yes, there should be an organizations association. The join is required because in the real application I'm adding a WHERE statement to it. I left it out here because it doesn't affect the problem I'm seeing.

I've tried setting up a small PR but so far I haven't been able to recreate the issue, but that is probably more because I'm not quite sure how to define the spec to emulate the index outlined in my original comment. But I did stumble onto another interesting observation:

In the index definition, if I in stead of this:

```ruby
indexes organizations.name, as: :practice_name, sortable: true
```

Reference the full path like this:

```ruby
indexes person_organizations.organization.name, as: :practice_name, sortable: true
```

.. then joiner 0.6.0 creates a functioning index. So it seems something has changed related to the handling of indexing has_many :through association directly, when also combined with a join like I have above?

**Comment by rogerkk** [comment]
Rails 6.1 / joiner 0.6.0 (working)

Here I'm referencing the full path when indexing:

```ruby
ThinkingSphinx::Index.define :doctor,
                             name: :doctor_ads,
                             with: :active_record,
                             delta: ThinkingSphinx::Deltas::DelayedDelta do

  indexes person_organizations.organization.name, as: :practice_name, sortable: true # This is changed from the examples above

  join search_advertisement_deal # Without this the generated config seems fine even if the organization name above is referenced directly like ```indexes organizations.name ...```
end
```

**Comment by rogerkk** [comment]
Not sure if this is helping at all, or if I'm just confusing you even more. 

I'll try to make some time to get that failing spec set up this week or the next, but I might require some assistance to get all the way there. Anyway I seem to have a workaround for the time being, so if this doesn't feel very interesting to look into anyway then I won't hold it against you if you close the issue. 😅

**Comment by pat** [comment]
Given you've found a workaround, I'm not too worried either way - it certainly means it's not such a priority for me 😅

Though I wonder if Joiner could detect if the applied association was a has-many-through and instead expanded it to the full association path. 🤔

**Comment by pat** [comment]
Wrote a very basic test involving a has-many-through association in 051e70697867db1b84de2df54ae595023c6a876d, and it seems to work fine with Rails 6.1 and 7.0. That said, it's not as involved as the situation you've been facing. I wonder if the polymorphic aspects is what's getting in the way? Even though it's the reverse side of the polymorphic association.

**Comment by rogerkk** [comment]
Oh, that's interesting! I'll see if I can expand on that test at some point, unfortunately I'm unable to prioritize this right now. :panda_face:

**Comment by rogerkk** [comment]
Well, I never got around to this and I figure it's rather unlikely that I'll be able to set off the time to look into this. Closing the issue to clean up a little here.
