### ISSUE TITLE
Bug with 0.4.1

### ISSUE THREAD

**Issue by kortirso** [pat/joiner#6]
Hi, I have bug with ruby 2.5.1, rails 5.2.0 and joiner 0.4.1 like it was at https://github.com/pat/joiner/issues/5
downgrading to 0.4.0 solves problem

rake ts:configure
Generating configuration to development.sphinx.conf
rake aborted!
ArgumentError: wrong number of arguments (given 3, expected 4)
/Users/kortirso/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency.rb:91:in `initialize'
/Users/kortirso/.rvm/gems/ruby-2.5.1/gems/joiner-0.4.1/lib/joiner/joins.rb:26:in `new'
/Users/kortirso/.rvm/gems/ruby-2.5.1/gems/joiner-0.4.1/lib/joiner/joins.rb:26:in `join_values'

**Comment by pat** [comment]
Ah, fair call. I'll try to get a 0.4.2 release out soon that works with both ActiveRecord 5.2.0 and 5.2.1.

**Comment by pat** [comment]
Just released 0.4.2, which works with both ActiveRecord 5.2.0 and 5.2.1 :)
